// Code generated by command: go run asm2.go -out search2.s -stubs stub_search2.go. DO NOT EDIT.

package simd

// Search finds the first idx for which xs[idx] >= k in xs.
func Search(xs []uint64, k uint64) int16
