// +build amd64

// Code generated by command: go run asm2.go -out search.s -stubs stub_search.go. DO NOT EDIT.

package simd

// Search finds the first idx for which xs[idx] >= k in xs.
func Search(xs []uint64, k uint64) int16
