// Code generated by command: go run asm.go -out sum.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Search(xs []uint64, k uint64) int16
TEXT ·Search(SB), NOSPLIT, $0-34
	// Base
	MOVQ xs_base+0(FP), AX

	// n
	MOVQ xs_len+8(FP), CX

	// Key
	MOVQ k+24(FP), DX

	// Initialize idx register to zero.
	XORL SI, SI
	JMP  check

plusplus:
	INCL SI

check:
	// REPLACE THE FOLLOWING TWO INSTRUCTIONS:  CMPQ idx n
	CMPQ SI, CX
	JGE  NotFound
	MOVQ (AX)(SI*8), BX
	NOP
	CMPQ BX, DX
	JCS  plusplus

	// Replace instructions with MOVW, tmp with idx
	MOVW SI, ret+32(FP)
	RET

NotFound:
	// Replace instructions with MOVW, tmp with $-1
	MOVW $-1, ret+32(FP)
	RET
