// Code generated by command: go run asm.go -out sum.s -stubs stub.go. DO NOT EDIT.

package simd

// Search finds the first idx for which xs[idx] >= k in xs.
func Search(xs []uint64, k uint64) int16
