// Code generated by command: go run asm.go -out sum.s -stubs stub.go. DO NOT EDIT.

#include "textflag.h"

// func Search(xs []uint64, k uint64) int16
TEXT ·Search(SB), NOSPLIT, $0-34
	MOVQ xs_base+0(FP), AX
	MOVQ xs_len+8(FP), CX
	MOVQ k+24(FP), DX

	// Initialize idx register to zero.
	XORW BX, BX

loop:
	// Loop until zero bytes remain.
	CMPQ CX, $0x00
	JLE  done

	// Load from pointer and add to running sum.
	CMPQ (AX), DX
	JAE  done

	// Advance pointer, decrement byte count.
	ADDQ $0x10, AX
	SUBQ $0x02, CX
	ADDW $0x01, BX
	JMP  loop

done:
	// Store sum to return value.
	MOVW BX, ret+32(FP)
	RET
